select * from customer

-- Q1. What is the total revenue generated by male vs.female customers;
select gender, sum(purchase_amount) as revenue
From customer
Group BY gender

-- Q2. Which customer's used a discount but still spend more than average purchase amount
Select customer_id, purchase_amount 
from customer
where discount_applied = 'yes' and purchase_amount >= (
select avg(purchase_amount) from customer
)

-- Q3. Which are the top 5 product with highest average rating?
SELECT item_purchased, ROUND(avg(review_rating::numeric),2) as Avg_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amount between Standard and Express Shipping
select avg(purchase_amount), shipping_type
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Q5. Do Subscribe the customers spend more? Compare average speed and totol revenue 
--     between subscriber and non-subcribers.
SELECT subscription_status,
	Count(customer_id) as total_customer,
	round(AVG(purchase_amount),2) as Avg_purchase,
	round(sum(purchase_amount),2) as sum_purchase
from customer
group by subscription_status
order by avg_purchase, sum_purchase desc;
	
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
	round(100 * sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from Customer
GROUP by item_purchased
order by discount_rate desc
limit 5

-- Q7. Segment customers into new, Returning, and Loyal based on there total number of previous
--     purchases, and show the count of each segment.

with customer_type as (
Select customer_id, previous_purchases,
	Case
		WHEN previous_purchases = 1 Then 'New'
		WHEN previous_purchases between 2 and 10 Then 'Returning'
		Else 'Loyal'
	END AS customer_segment
From customer
)
SELECT customer_segment, count(*) as "Number of Customer"
from customer_type
group by customer_segment

-- Q8. What are top 3 most purchased product with each category?
with items_count as(
select category, 
	item_purchased,
	count(Customer_id) as total_order,
	ROW_NUMBER() OVER(Partition by category order by count(customer_id) DESC) AS item_rnk
from customer
group by category, item_purchased
)
select category, item_purchased, total_order, item_rnk
from items_count
where item_rnk <= 3

-- Q9. Are Customers who are repeat buyers (more than 5 previous purchased) also likely to subscribe?
Select subscription_status,
	Count(customer_id) as repeted_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- 10. what is the revenue contribution of each age group?
Select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue DESC



